name: figure_collections_maps
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  google_maps_flutter: ^2.1.1
  geocoding: ^2.0.2
  flutter_slidable: ^1.2.0
  grouped_list: ^4.2.0
  firebase_core: ^2.2.0
  firebase_auth: ^4.1.2
  provider: ^6.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true